import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowUpRight, Check, Flame, Plus, Target, Trash2, X } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { apiDelete, apiGet, apiPost, apiPut } from "@/lib/api";
import type { CompletionToggle, DashboardStats, Habit } from "@/lib/types";
import { queryClient } from "@/lib/queryClient";

const emptyStats: DashboardStats = { today_completed: 0, today_total: 0, active_streak: 0, consistency: 0, weekly_progress: [] };

export default function Dashboard() {
  const [editing, setEditing] = useState<string | null>(null);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [color, setColor] = useState("#007AFF");
  const habitsQuery = useQuery({ queryKey: ["habits"], queryFn: () => apiGet<Habit[]>("/habits"), retry: false });
  const statsQuery = useQuery({ queryKey: ["dashboard"], queryFn: () => apiGet<DashboardStats>("/habits/dashboard"), retry: false });
  const habits = habitsQuery.data ?? [];
  const stats = statsQuery.data ?? emptyStats;
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ["habits"] }); void queryClient.invalidateQueries({ queryKey: ["dashboard"] }); void queryClient.invalidateQueries({ queryKey: ["history"] }); void queryClient.invalidateQueries({ queryKey: ["leaderboard"] }); };
  const saveHabit = useMutation({
    mutationFn: () => editing ? apiPut<Habit>(`/habits/${editing}`, { name, description, color }) : apiPost<Habit>("/habits", { name, description, color }),
    onSuccess: () => { refresh(); setEditing(null); setName(""); setDescription(""); toast.success(editing ? "Habit updated" : "Habit added to today"); },
    onError: () => toast.error("Could not save this habit"),
  });
  const toggle = useMutation({ mutationFn: (id: string) => apiPost<CompletionToggle>(`/habits/${id}/complete`), onSuccess: (result) => { refresh(); toast.success(result.completed ? "Completed. Keep the streak alive." : "Completion removed"); }, onError: () => toast.error("Could not update completion") });
  const remove = useMutation({ mutationFn: (id: string) => apiDelete<void>(`/habits/${id}`), onSuccess: () => { refresh(); toast.success("Habit deleted"); }, onError: () => toast.error("Could not delete habit") });

  const editHabit = (habit: Habit) => { setEditing(habit.id); setName(habit.name); setDescription(habit.description); setColor(habit.color); window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" }); };
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (name.trim()) saveHabit.mutate(); };

  return <div className="mx-auto max-w-[1440px]" data-testid="dashboard-page">
    <div className="mb-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-3 text-[10px] font-bold uppercase tracking-[0.28em] text-[#007aff]" data-testid="dashboard-eyebrow">Daily command center / {new Date().toLocaleDateString("en-US", { weekday: "long", month: "short", day: "numeric" })}</p><h1 className="font-heading text-5xl font-black uppercase leading-none tracking-tight sm:text-6xl" data-testid="dashboard-title">Stay in motion.</h1><p className="mt-4 max-w-lg text-sm leading-relaxed text-[#8a8a8e]" data-testid="dashboard-subtitle">Small actions. Measurable momentum. Complete today’s set and protect your run.</p></div><div className="flex items-center gap-2 border border-[#262626] bg-[#141414] px-4 py-3 text-xs text-[#8a8a8e]" data-testid="dashboard-date-status"><span className="size-2 rounded-full bg-[#007aff]" />Today is live</div></div>
    <section className="mb-6 grid gap-px border border-[#262626] bg-[#262626] md:grid-cols-3" data-testid="metrics-grid">
      {[{ label: "Active streak", value: stats.active_streak, suffix: "days", icon: Flame, accent: "text-[#ff3b30]" }, { label: "Today's score", value: `${stats.today_completed}/${stats.today_total}`, suffix: "complete", icon: Target, accent: "text-[#007aff]" }, { label: "7-day consistency", value: `${stats.consistency}%`, suffix: "pace", icon: ArrowUpRight, accent: "text-[#007aff]" }].map(({ label, value, suffix, icon: Icon, accent }) => <div className="bg-[#141414] p-6 transition-transform duration-200 hover:-translate-y-1" key={label} data-testid={`metric-${label.toLowerCase().replaceAll(" ", "-")}`}><div className="mb-8 flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#8a8a8e]">{label}</span><Icon size={17} className={accent} /></div><p className="font-heading text-5xl font-black leading-none" data-testid={`metric-value-${label.toLowerCase().replaceAll(" ", "-")}`}>{value}</p><p className="mt-3 text-xs uppercase tracking-[0.15em] text-[#555]">{suffix}</p></div>)}
    </section>

    <section className="mb-6 grid gap-6 xl:grid-cols-[1.45fr_0.8fr]">
      <div className="border border-[#262626] bg-[#141414]" data-testid="today-habits-panel"><div className="flex items-center justify-between border-b border-[#262626] p-6"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#8a8a8e]">Execution list</p><h2 className="mt-2 font-heading text-2xl font-black uppercase" data-testid="today-habits-title">Today's habits</h2></div><span className="font-mono text-xs text-[#007aff]" data-testid="habit-count-label">{habits.length.toString().padStart(2, "0")} loaded</span></div><div data-testid="habit-list">{habits.length === 0 ? <div className="p-8 text-sm text-[#8a8a8e]" data-testid="empty-habits-state">No habits on the board yet. Add your first one below.</div> : habits.map((habit, index) => <div key={habit.id} className="group flex items-center gap-4 border-b border-[#262626] p-5 transition-[background-color,border-color] hover:border-l-2 hover:border-l-[#007aff] hover:bg-[#191919]" data-testid={`habit-row-${habit.id}`}><button type="button" onClick={() => toggle.mutate(habit.id)} className={`grid size-8 shrink-0 place-items-center border transition-[background-color,transform] duration-200 active:scale-90 ${habit.completed_today ? "border-[#007aff] bg-[#007aff] text-white" : "border-[#454545] text-transparent hover:border-[#007aff]"}`} style={{ borderColor: habit.completed_today ? habit.color : undefined, backgroundColor: habit.completed_today ? habit.color : undefined }} data-testid={`habit-toggle-${habit.id}`} aria-label={`Toggle ${habit.name}`}><Check size={16} strokeWidth={3} /></button><div className="min-w-0 flex-1"><p className={`font-semibold ${habit.completed_today ? "text-[#8a8a8e] line-through" : "text-white"}`} data-testid={`habit-name-${habit.id}`}>{habit.name}</p><p className="mt-1 truncate text-xs text-[#555]" data-testid={`habit-description-${habit.id}`}>{habit.description || "No details added"}</p></div><div className="hidden text-right sm:block"><p className="font-mono text-xs text-[#8a8a8e]" data-testid={`habit-streak-${habit.id}`}>{habit.current_streak} day streak</p><p className="mt-1 text-[10px] uppercase tracking-[0.13em] text-[#555]">{habit.total_completions} total</p></div><button type="button" onClick={() => editHabit(habit)} className="p-2 text-[#555] transition-colors hover:text-white" data-testid={`habit-edit-${habit.id}`} aria-label={`Edit ${habit.name}`}><span className="text-[10px] font-bold uppercase tracking-widest">Edit</span></button><button type="button" onClick={() => remove.mutate(habit.id)} className="p-2 text-[#555] transition-colors hover:text-[#ff3b30]" data-testid={`habit-delete-${habit.id}`} aria-label={`Delete ${habit.name}`}><Trash2 size={16} /></button></div>)}</div></div>
      <div className="border border-[#262626] bg-[#141414] p-6" data-testid="weekly-progress-panel"><div className="mb-8 flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#8a8a8e]">Signal / last 7 days</p><h2 className="mt-2 font-heading text-2xl font-black uppercase">Weekly pace</h2></div><ArrowUpRight size={18} className="text-[#007aff]" /></div><div className="flex h-44 items-end gap-2 border-b border-l border-[#262626] px-3 pb-0 pt-4" data-testid="weekly-progress-chart">{stats.weekly_progress.length === 0 ? <div className="mb-5 text-xs text-[#555]" data-testid="empty-chart-state">Add habits to see your pace.</div> : stats.weekly_progress.map((point) => <div className="flex h-full flex-1 flex-col items-center justify-end gap-2" key={point.date} data-testid={`weekly-bar-${point.date}`}><div className="w-full max-w-7 rounded-t-sm bg-[#007aff] transition-[height] duration-300" style={{ height: `${point.total ? Math.max(8, (point.completed / point.total) * 100) : 8}%`, opacity: point.completed ? 1 : 0.18 }} title={`${point.completed} of ${point.total}`} /><span className="font-mono text-[9px] text-[#555]">{point.label.slice(0, 1)}</span></div>)}</div><div className="mt-5 flex justify-between text-[10px] uppercase tracking-[0.15em] text-[#555]"><span>Low friction</span><span data-testid="weekly-summary">{stats.weekly_progress.reduce((sum, point) => sum + point.completed, 0)} completions</span></div></div>
    </section>

    <section className="border border-[#262626] bg-[#141414]" data-testid="habit-editor-panel"><div className="flex items-center justify-between border-b border-[#262626] p-6"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#8a8a8e]">System builder</p><h2 className="mt-2 font-heading text-2xl font-black uppercase">{editing ? "Tune habit" : "Add a habit"}</h2></div>{editing && <button type="button" onClick={() => { setEditing(null); setName(""); setDescription(""); }} className="text-[#8a8a8e] hover:text-white" data-testid="habit-editor-cancel-button" aria-label="Cancel editing"><X size={18} /></button>}</div><form onSubmit={submit} className="grid gap-4 p-6 md:grid-cols-[1fr_1.3fr_120px_auto] md:items-end" data-testid="habit-form"><label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[0.18em] text-[#8a8a8e]">Habit name</span><Input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Read 20 pages" className="h-11 rounded-none border-[#262626] bg-[#0f0f10]" data-testid="habit-name-input" /></label><label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[0.18em] text-[#8a8a8e]">Description</span><Textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Make time for the long game" className="min-h-11 resize-none rounded-none border-[#262626] bg-[#0f0f10]" data-testid="habit-description-input" /></label><label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[0.18em] text-[#8a8a8e]">Color</span><Input type="color" value={color} onChange={(event) => setColor(event.target.value)} className="h-11 w-full rounded-none border-[#262626] bg-[#0f0f10] p-1" data-testid="habit-color-input" /></label><Button type="submit" disabled={saveHabit.isPending} className="h-11 rounded-none bg-[#007aff] font-bold uppercase tracking-[0.12em] text-white hover:bg-[#1990ff] hover:text-white" data-testid="habit-form-submit-button">{editing ? <><Check size={16} />Save</> : <><Plus size={16} />Add habit</>}</Button></form></section>
  </div>;
}