import { useQuery } from "@tanstack/react-query";
import { CalendarDays, Check, History as HistoryIcon } from "lucide-react";
import { apiGet } from "@/lib/api";
import type { CompletionRecord } from "@/lib/types";

export default function History() {
  const query = useQuery({ queryKey: ["history"], queryFn: () => apiGet<CompletionRecord[]>("/habits/history"), retry: false });
  const records = query.data ?? [];
  const grouped = records.reduce<Record<string, CompletionRecord[]>>((acc, record) => { (acc[record.date] ??= []).push(record); return acc; }, {});
  return <div className="mx-auto max-w-[1100px]" data-testid="history-page"><div className="mb-10"><p className="mb-3 text-[10px] font-bold uppercase tracking-[0.28em] text-[#007aff]" data-testid="history-eyebrow">Archive / completed work</p><h1 className="font-heading text-5xl font-black uppercase leading-none tracking-tight" data-testid="history-title">Your proof.</h1><p className="mt-4 max-w-lg text-sm leading-relaxed text-[#8a8a8e]" data-testid="history-subtitle">A clean record of every time you chose to keep the promise.</p></div><div className="grid gap-6 lg:grid-cols-[0.7fr_1.3fr]"><section className="border border-[#262626] bg-[#141414] p-6" data-testid="history-summary"><HistoryIcon className="mb-12 text-[#007aff]" size={20} /><p className="font-heading text-6xl font-black" data-testid="history-total-count">{records.length.toString().padStart(2, "0")}</p><p className="mt-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#8a8a8e]">Total completions</p><div className="mt-10 border-t border-[#262626] pt-5 text-xs leading-relaxed text-[#8a8a8e]" data-testid="history-summary-copy">Every entry is date-stamped and tied to a single habit. No duplicates. No noise.</div></section><section className="border border-[#262626] bg-[#141414]" data-testid="history-log"><div className="border-b border-[#262626] p-6"><div className="flex items-center gap-3"><CalendarDays size={18} className="text-[#007aff]" /><h2 className="font-heading text-2xl font-black uppercase">Completion log</h2></div></div>{Object.keys(grouped).length === 0 ? <div className="p-8 text-sm text-[#8a8a8e]" data-testid="empty-history-state">Your history will appear here after your first completion.</div> : <div>{Object.entries(grouped).map(([date, items]) => <div className="border-b border-[#262626] p-6 last:border-b-0" key={date} data-testid={`history-date-${date}`}><div className="mb-4 flex items-center justify-between"><p className="font-mono text-xs text-[#007aff]">{new Date(`${date}T12:00:00`).toLocaleDateString("en-US", { weekday: "long", month: "short", day: "numeric" })}</p><span className="text-[10px] uppercase tracking-[0.16em] text-[#555]">{items.length} done</span></div><div className="space-y-3">{items.map((item) => <div className="flex items-center gap-3" key={item.id} data-testid={`history-entry-${item.id}`}><span className="grid size-5 place-items-center rounded-full" style={{ backgroundColor: `${item.color}22`, color: item.color }}><Check size={12} /></span><span className="text-sm" data-testid={`history-habit-name-${item.id}`}>{item.habit_name}</span></div>)}</div></div>)}</div>}</section></div></div>;
}